version: "2"
services:
    php-fpm:
        image: lordius/alpine-php_fpm:php-7
        links:
            - mysql            
        depends_on:
            - mysql
        volumes:
            - .:/var/www/localhost/
        environment:
            DRUSH_VERSION: 8.x
            PHP_SHOW_ERRORS: 1
            CRONTAB_ENABLED: 0
            PHP_FPM_PORT: 7000
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -i -t
            PHP_SENDMAIL_HOST: sendmail
            PHP_SENDMAIL_PORT: 1025
            PHP_XDEBUG_ENABLED: 1
            PHP_XDEBUG_PORT: 9000
            PHP_MAX_EXECUTION_TIME: 250
            PHP_UPLOAD_MAX_FILESIZE: 1024M
            PHP_POST_MAX_SIZE: 756M
            PHP_ALLOW_URL_FOPEN: "On"
            PHP_ALWAYS_POPULATE_RAW_POST_DATA: -1
            PHP_SHORT_OPEN_TAG: 1
            PHP_MEMORY_LIMIT: 1024M
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.2
        extra_hosts:
            - "site.dockerlamp:172.55.0.4" 
    apache2_mpm:
        image: lordius/alpine-apache
        links:
            - php-fpm
            - mysql
        depends_on:
            - php-fpm
        volumes_from:
            - php-fpm
        environment:
            APACHE_TIMEOUT: 300
            DOCUMENT_ROOT: /var/www/localhost/public
            PROXY_PASS: fcgi://php-fpm:7000/var/www/localhost/public
            APACHE_LISTEN_PORT: 80
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.3
        ports:
            - 8000:80
              
################ Database images.
    mysql:
        image: mysql
        volumes:
            - ./docker/runtime/mysql/lib:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: testdrive
            MYSQL_PASSWORD: testdrive
            MYSQL_DATABASE: testdrive
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.100
        ports:
         - 42333:3306
         
networks:
  internal:
    driver_opts:
      internal: "true"
    driver: bridge      
  shared:
    driver_opts:
      enable_ipv6: "true"
    driver: bridge
    ipam:
     config:
       - subnet: 172.55.0.0/16
         gateway: 172.55.0.1